#pragma once
#include "Core/BlitzenEngine.h"
#include "Platform/Common/blitMappedFile.h"
#include "Renderer/Resources/blitShaderResources.h"
#include "BlitCL/blitString.h"
#include "Renderer/Resources/Mesh/blitMeshes.h"

namespace BlitzenEngine
{
	constexpr const char* GcRapidMeshFileExtension = ".blitMesh";
	constexpr size_t GcRapidMeshFileSizeThreshold = 1024 * 1024 * 10; // 10 MB (Probably too much but oh well, it's just for checking)
    constexpr size_t GcRapidMeshFileHeaderSize = 1000;
    constexpr size_t CE_BLITZEN_RAPID_MESH_FILE_PADDING_SIZE = 1000;
    constexpr const char* GCRapidMeshDirectoryPath = BLITZEN_CLIENT_RPFMESH_DIRECTORY;
    constexpr uint32_t GCImportedSceneNodesHeaderElementCount = 4;
    constexpr const char* GCImportedSceneNodesFileName = "nodes.blitnr";

    // Straight enum for ease of use
    enum BLIT_RPF_MESH_FILE_HEADER_IDS
    {
        BLIT_RPF_MESH_FILE_HEADER_MESH_PRIMITIVE_ID = 0,
        BLIT_RPF_MESH_FILE_HEADER_MESH_PRIMITIVE_DATA_ID = 1,
        BLIT_RPF_MESH_FILE_HEADER_LOD_DATA_ID = 2,
        BLIT_RPF_MESH_FILE_HEADER_BOUNDING_SPHERE_ID = 3,
        BLIT_RPF_MESH_FILE_HEADER_VTX_POS_DATA_ID = 4,
        BLIT_RPF_MESH_FILE_HEADER_VTX_NRM_DATA_ID = 5,
        BLIT_RPF_MESH_FILE_HEADER_VTX_TNG_DATA_ID = 6,
        BLIT_RPF_MESH_FILE_HEADER_VTX_COORD_DATA_ID = 7,
        BLIT_RPF_MESH_FILE_HEADER_VTX_IDXS_DATA_ID = 8,
        BLIT_RPF_MESH_FILE_HEADER_CLUSTER_VTXS_DATA_ID = 9,
        BLIT_RPF_MESH_FILE_HEADER_CLUSTER_SPHERES_DATA_ID = 10,
        BLIT_RPF_MESH_FILE_HEADER_CLUSTER_CONES_DATA_ID = 11,
        BLIT_RPF_MESH_FILE_HEADER_CLUSTER_IDXS_DATA_ID = 12,
        BLIT_RPF_MESH_FILE_HEADER_COLLIDER_AMAXRAD_DATA_ID = 13,
        BLIT_RPF_MESH_FILE_HEADER_COLLIDER_BMINTYPE_DATA_ID = 14,

        BLIT_RPF_MESH_FILE_HEADER_MAX = 15
    };
    constexpr uint32_t GCRapidMeshFileHeaderElementCount = BLIT_RPF_MESH_FILE_HEADER_MAX;
    static_assert(GCRapidMeshFileHeaderElementCount * sizeof(size_t) < GcRapidMeshFileHeaderSize);

    using BLIT_RPF_MESH_FILE_HEADER_ARR = size_t[GCRapidMeshFileHeaderElementCount];

    constexpr size_t CE_GET_RPF_MESH_SIZE_ERROR_RETURN_CODE = GcRapidMeshFileSizeThreshold;
	size_t GetRpfMeshSize(MeshResources& rpfCtx, bool clustersBuildFlag);

    // Receives a string container to hold the contents and returns the path based on the mesh's name
    // The return is what the container will be holding by the end of the function
    const char* GetRpfMeshPath(const char* meshName, BlitCL::String& stringContainer);

    enum class LOAD_MESH_FROM_DISK_RES : int32_t
    {
        SUCCESS = BlitzenCore::CE_BLITZEN_SUCCESS,
        FATAL = BlitzenCore::CE_BLITZEN_FATAL,
        FAILED_TO_OPEN_FILE = BlitzenCore::CE_BLITZEN_FATAL - 100,

        FAILED_TO_READ_HEADER = -1,
        FAILED_TO_READ_MESH_PRIMITIVE = -2,
        FAILED_TO_READ_MESH_PRIMITIVE_NON_SHADER_DATA = -3,
        FAILED_TO_READ_LOD_DATA = -4,
        FAILED_TO_READ_VISIBILITY_BOUNDING_SPHERE = -5,
        FAILED_TO_READ_VERTEX_POSITIONS = -6,
        FAILED_TO_READ_VERTEX_NORMALS = -7,
        FAILED_TO_READ_VERTEX_TANGENTS = -8,
        FAILED_TO_READ_VERTEX_TEXTURE_COORDINATES = -9,
        FAILED_TO_READ_VERTEX_INDICES = -10,
        FAILED_TO_READ_CLUSTER_VERTICES = -11,
        FAILED_TO_READ_CLUSTER_SPHERES = -12,
        FAILED_TO_READ_CLUSTER_CONES = -13,
        FAILED_TO_READ_CLUSTER_INDICES = -14,
        FAILED_TO_READ_COLLIDER_AMAXRAD_DATA = -15,
        FAILED_TO_READ_COLLIDER_BMINTYPE_DATA = -16,

        LOD_CONTEXT_NOT_RESET_BEFORE_LOAD_OPERATION = BlitzenCore::CE_BLITZEN_FATAL + 1,
    };
    LOAD_MESH_FROM_DISK_RES LoadMeshFromDisk(const char* meshName, BlitzenPlatform::MEMORY_MAPPED_FILE_SCOPE& memoryMappedFile, MeshResources& context);

    enum class UPLOAD_MESH_TO_DISK_RES : int64_t
    {
        SUCCESS = BlitzenCore::CE_BLITZEN_SUCCESS,
        FATAL = BlitzenCore::CE_BLITZEN_FATAL,
        FAILED_TO_OPEN_FILE = BlitzenCore::CE_BLITZEN_FATAL - 100,

        UPLOAD_SIZE_TOO_BIG = -1,
        FAILED_TO_UPLOAD_MESH_PRIMITIVES = -2,
        FAILED_TO_UPLOAD_MESH_PRIMITIVE_DATA = -3,
        FAILED_TO_UPLOAD_LOD_DATA = -4,
        FAILED_TO_UPLOAD_BOUNDING_SPHERE_DATA = -5,
        FAILED_TO_UPLOAD_VERTEX_POSITIONS_DATA = -6,
        FAILED_TO_UPLOAD_VERTEX_NORMALS_DATA = -7,
        FAILED_TO_UPLOAD_VERTEX_TANGENTS_DATA = -8,
        FAILED_TO_UPLOAD_VERTEX_TEXTURE_COORDINATES_DATA = -9,
        FAILED_TO_UPLOAD_VERTEX_INDICES = -10,
        FAILED_TO_UPLOAD_CLUSTER_VERTEX_DATA = -11,
        FAILED_TO_UPLOAD_CLUSTER_SPHERES = -12,
        FAILED_TO_UPLOAD_CLUSTER_CONES = -13,
        FAILED_TO_UPLOAD_CLUSTER_INDICES = -14,
        FAILED_TO_UPLOAD_OFFSETS_TO_HEADER = -15,
        FAILED_TO_UPLOAD_COLLIDER_AMAXRAD_DATA = -16,
        FAILED_TO_UPLOAD_COLLIDER_BMINTYPE_DATA = -17,
    };
    UPLOAD_MESH_TO_DISK_RES UploadMeshToDisk(const char* meshName, BlitzenPlatform::MEMORY_MAPPED_FILE_SCOPE& memoryMappedFile, MeshResources& context, bool clustersBuildFlag);

    inline const char* LOAD_MESH_FROM_STRING_RES_TO_STRING(LOAD_MESH_FROM_DISK_RES res)
    {
        switch (res)
        {
        case LOAD_MESH_FROM_DISK_RES::SUCCESS: return "LOAD_MESH_FROM_DISK_RES::SUCCESS";
        case LOAD_MESH_FROM_DISK_RES::FATAL: return "LOAD_MESH_FROM_DISK_RES::FATAL";
        case LOAD_MESH_FROM_DISK_RES::FAILED_TO_OPEN_FILE: return "LOAD_MESH_FROM_DISK_RES::FAILED_TO_OPEN_FILE";
        case LOAD_MESH_FROM_DISK_RES::FAILED_TO_READ_HEADER: return "LOAD_MESH_FROM_DISK_RES::FAILED_TO_READ_HEADER";
        case LOAD_MESH_FROM_DISK_RES::FAILED_TO_READ_MESH_PRIMITIVE: return "LOAD_MESH_FROM_DISK_RES::FAILED_TO_READ_MESH_PRIMITIVE";
        case LOAD_MESH_FROM_DISK_RES::FAILED_TO_READ_MESH_PRIMITIVE_NON_SHADER_DATA: return "LOAD_MESH_FROM_DISK_RES::FAILED_TO_READ_MESH_PRIMITIVE_NON_SHADER_DATA";
        case LOAD_MESH_FROM_DISK_RES::LOD_CONTEXT_NOT_RESET_BEFORE_LOAD_OPERATION: return "LOAD_MESH_FROM_DISK_RES::LOD_CONTEXT_NOT_RESET_BEFORE_LOAD_OPERATION";
        case LOAD_MESH_FROM_DISK_RES::FAILED_TO_READ_LOD_DATA: return "LOAD_MESH_FROM_DISK_RES::FAILED_TO_READ_LOD_DATA";
        case LOAD_MESH_FROM_DISK_RES::FAILED_TO_READ_VISIBILITY_BOUNDING_SPHERE: return "LOAD_MESH_FROM_DISK_RES::FAILED_TO_READ_VISIBILITY_BOUNDING_SPHERE";
        case LOAD_MESH_FROM_DISK_RES::FAILED_TO_READ_VERTEX_POSITIONS: return "LOAD_MESH_FROM_DISK_RES::FAILED_TO_READ_VERTEX_POSITIONS";
        case LOAD_MESH_FROM_DISK_RES::FAILED_TO_READ_VERTEX_NORMALS: return "LOAD_MESH_FROM_DISK_RES::FAILED_TO_READ_VERTEX_NORMALS";
        case LOAD_MESH_FROM_DISK_RES::FAILED_TO_READ_VERTEX_TANGENTS: return "LOAD_MESH_FROM_DISK_RES::FAILED_TO_READ_VERTEX_TANGENTS";
        case LOAD_MESH_FROM_DISK_RES::FAILED_TO_READ_VERTEX_TEXTURE_COORDINATES: return "LOAD_MESH_FROM_DISK_RES::FAILED_TO_READ_VERTEX_TEXTURE_COORDINATES";
        case LOAD_MESH_FROM_DISK_RES::FAILED_TO_READ_VERTEX_INDICES: return "LOAD_MESH_FROM_DISK_RES::FAILED_TO_READ_VERTEX_INDICES";
        case LOAD_MESH_FROM_DISK_RES::FAILED_TO_READ_CLUSTER_VERTICES: return "LOAD_MESH_FROM_DISK_RES::FAILED_TO_READ_CLUSTER_VERTICES";
        case LOAD_MESH_FROM_DISK_RES::FAILED_TO_READ_CLUSTER_SPHERES: return "LOAD_MESH_FROM_DISK_RES::FAILED_TO_READ_CLUSTER_SPHERES";
        case LOAD_MESH_FROM_DISK_RES::FAILED_TO_READ_CLUSTER_CONES: return "LOAD_MESH_FROM_DISK_RES::FAILED_TO_READ_CLUSTER_CONES";
        case LOAD_MESH_FROM_DISK_RES::FAILED_TO_READ_CLUSTER_INDICES: return "LOAD_MESH_FROM_DISK_RES::FAILED_TO_READ_CLUSTER_INDICES";
        case LOAD_MESH_FROM_DISK_RES::FAILED_TO_READ_COLLIDER_AMAXRAD_DATA: return "LOAD_MESH_FROM_DISK_RES::FAILED_TO_READ_COLLIDER_AMAXRAD_DATA";
        case LOAD_MESH_FROM_DISK_RES::FAILED_TO_READ_COLLIDER_BMINTYPE_DATA: return "LOAD_MESH_FROM_DISK_RES::FAILED_TO_READ_COLLIDER_BMINTYPE_DATA";
        default: return "LOAD_MESH_FROM_DISK_RES::UNKNOW";
        }
    }

    inline const char* UPLOAD_MESH_TO_DISK_RES_TO_STRING(UPLOAD_MESH_TO_DISK_RES res)
    {
        switch (res)
        {
        case UPLOAD_MESH_TO_DISK_RES::SUCCESS: return "UPLOAD_MESH_TO_DISK_RES::SUCCESS";
        case UPLOAD_MESH_TO_DISK_RES::FATAL: return "UPLOAD_MESH_TO_DISK_RES::FATAL";
        case UPLOAD_MESH_TO_DISK_RES::FAILED_TO_OPEN_FILE: return "UPLOAD_MESH_TO_DISK_RES::FAILED_TO_OPEN_FILE";
        case UPLOAD_MESH_TO_DISK_RES::UPLOAD_SIZE_TOO_BIG: return "UPLOAD_MESH_TO_DISK_RES::UPLOAD_SIZE_TOO_BIG";
        case UPLOAD_MESH_TO_DISK_RES::FAILED_TO_UPLOAD_MESH_PRIMITIVES: return "UPLOAD_MESH_TO_DISK_RES::FAILED_TO_UPLOAD_MESH_PRIMITIVES";
        case UPLOAD_MESH_TO_DISK_RES::FAILED_TO_UPLOAD_MESH_PRIMITIVE_DATA: return "UPLOAD_MESH_TO_DISK_RES::FAILED_TO_UPLOAD_MESH_PRIMITIVE_DATA";
        case UPLOAD_MESH_TO_DISK_RES::FAILED_TO_UPLOAD_LOD_DATA: return "UPLOAD_MESH_TO_DISK_RES::FAILED_TO_UPLOAD_LOD_DATA";
        case UPLOAD_MESH_TO_DISK_RES::FAILED_TO_UPLOAD_BOUNDING_SPHERE_DATA: return "UPLOAD_MESH_TO_DISK_RES::FAILED_TO_UPLOAD_BOUNDING_SPHERE_DATA";
        case UPLOAD_MESH_TO_DISK_RES::FAILED_TO_UPLOAD_VERTEX_POSITIONS_DATA: return "UPLOAD_MESH_TO_DISK_RES::FAILED_TO_UPLOAD_VERTEX_POSITIONS_DATA";
        case UPLOAD_MESH_TO_DISK_RES::FAILED_TO_UPLOAD_VERTEX_NORMALS_DATA: return "UPLOAD_MESH_TO_DISK_RES::FAILED_TO_UPLOAD_VERTEX_NORMALS_DATA";
        case UPLOAD_MESH_TO_DISK_RES::FAILED_TO_UPLOAD_VERTEX_TANGENTS_DATA: return "UPLOAD_MESH_TO_DISK_RES::FAILED_TO_UPLOAD_VERTEX_TANGENTS_DATA";
        case UPLOAD_MESH_TO_DISK_RES::FAILED_TO_UPLOAD_VERTEX_TEXTURE_COORDINATES_DATA: return "UPLOAD_MESH_TO_DISK_RES::FAILED_TO_UPLOAD_VERTEX_TEXTURE_COORDINATES_DATA";
        case UPLOAD_MESH_TO_DISK_RES::FAILED_TO_UPLOAD_VERTEX_INDICES: return "UPLOAD_MESH_TO_DISK_RES::FAILED_TO_UPLOAD_VERTEX_INDICES";
        case UPLOAD_MESH_TO_DISK_RES::FAILED_TO_UPLOAD_CLUSTER_VERTEX_DATA: return "UPLOAD_MESH_TO_DISK_RES::FAILED_TO_UPLOAD_CLUSTER_VERTEX_DATA";
        case UPLOAD_MESH_TO_DISK_RES::FAILED_TO_UPLOAD_CLUSTER_SPHERES: return "UPLOAD_MESH_TO_DISK_RES::FAILED_TO_UPLOAD_CLUSTER_SPHERES";
        case UPLOAD_MESH_TO_DISK_RES::FAILED_TO_UPLOAD_CLUSTER_CONES: return "UPLOAD_MESH_TO_DISK_RES::FAILED_TO_UPLOAD_CLUSTER_CONES";
        case UPLOAD_MESH_TO_DISK_RES::FAILED_TO_UPLOAD_CLUSTER_INDICES: return "UPLOAD_MESH_TO_DISK_RES::FAILED_TO_UPLOAD_CLUSTER_INDICES";
        case UPLOAD_MESH_TO_DISK_RES::FAILED_TO_UPLOAD_OFFSETS_TO_HEADER: return "UPLOAD_MESH_TO_DISK_RES::FAILED_TO_UPLOAD_OFFSETS_TO_HEADER";
        case UPLOAD_MESH_TO_DISK_RES::FAILED_TO_UPLOAD_COLLIDER_AMAXRAD_DATA: return "UPLOAD_MESH_TO_DISK_RES::FAILED_TO_UPLOAD_COLLIDER_AMAXRAD_DATA";
        case UPLOAD_MESH_TO_DISK_RES::FAILED_TO_UPLOAD_COLLIDER_BMINTYPE_DATA: return "UPLOAD_MESH_TO_DISK_RES::FAILED_TO_UPLOAD_COLLIDER_BMINTYPE_DATA";
        default: return "UPLOAD_MESH_TO_DISK_RES::UNKNOWN";
        }
    }

    enum BLIT_RPF_IMPORTED_SCENE_NODES_HEADER
    {
        BlitRpfImportedSceneNodesHeaderNodeCountID = 0,
        BlitRpfImportedSceneNodesHeaderResourceCountID = 1,
        BlitRpfImportedSceneNodesHeaderRenderObjectsID = 2,
        BlitRpfImportedSceneNodesHeaderTransformsID = 3,

        BlitRpfImportedSceneNodesHeaderMax = 4
    };
    static_assert(BlitRpfImportedSceneNodesHeaderMax == GCImportedSceneNodesHeaderElementCount);

    using ImportedSceneNodesHeaderArr = size_t[GCImportedSceneNodesHeaderElementCount];

    // Takes resident data that is unique to an imported scene and uploads it to disk
    // This allows for Blitzen to keep the scene within its context on disk and update it when loading.
    BLIT_OFFLINE_FUNC bool UploadImportedSceneNodesToDisk(const char* sceneName, uint32_t resourceCount, uint32_t nodesCount, RenderObject* renderObjects, MeshTransform* meshTransforms);

    const char* BuildImportedSceneNodesFilepath(const char* sceneName, BlitCL::String& stringContainer);

    // FOR FUTURE REFERENCE. Probably v2
    struct MeshRpfOffsetAccessor
    {
        size_t m_offset;
        size_t m_count;
    };
    using BLIT_RPF_MESH_FILE_OFFSETS_ARR = MeshRpfOffsetAccessor[GCRapidMeshFileHeaderElementCount];

    constexpr const char* CE_RPF_MESH_CONTEXT_FILE_NAME = "Assets/BlitzenRapidMeshes/context.blitMesh";
    constexpr const char* CE_RPF_MESH_OFFSETS_FILE_NAME = "Assets/BlitzenRapidMeshes/offsets.blitMesh";
    constexpr const char* CE_RPF_MESH_ASSETS_FILE_NAME = "Assets/BlitzenRapidMeshes/assets.blitMesh";
    class MESH_RPF_OFFSET_MANAGER
    {
    public:
        BLIT_RPF_MESH_FILE_OFFSETS_ARR m_offsets;
        size_t offset;
        BlitzenPlatform::MEMORY_MAPPED_FILE_SCOPE m_offsetFile;
        BlitzenPlatform::MEMORY_MAPPED_FILE_SCOPE m_assetFile;

        void Startup();

        void CloseAndSave();

        // Might not be needed since the mmf already does destructor memory cleanup
        ~MESH_RPF_OFFSET_MANAGER();
    };
}