const uint BLIT_MAX_WORLD_RENDERS = 5000000;
const uint BLIT_MAX_WORLD_OPAQUE_STATIC_RENDERS = 4500000;
const uint BLIT_MAX_WORLD_TRANSPARENT_RENDERS = 10000;
const uint BLIT_MAX_WORLD_OPAQUE_DYNAMIC_RENDERS = 5000;
const uint BLIT_TRANSPARENT_RENDER_OFFSET = 0;
const uint BLIT_OPAQUE_DYNAMIC_RENDER_OFFSET = BLIT_MAX_WORLD_TRANSPARENT_RENDERS;
const uint BLIT_OPAQUE_STATIC_RENDER_OFFSET = BLIT_MAX_WORLD_TRANSPARENT_RENDERS + BLIT_MAX_WORLD_OPAQUE_DYNAMIC_RENDERS;
const uint BLIT_MAX_WORLD_TRANSFORM_COUNT = BLIT_MAX_WORLD_RENDERS;