#include "Renderer/BlitzenVulkan/vulkanRenderer.h"

namespace BlitzenVulkan
{
	using BLIT_VK_CULLING_FLAGS = int8_t;
	constexpr BLIT_VK_CULLING_FLAGS BLIT_VK_CULL_NOTHING = -1;
	constexpr BLIT_VK_CULLING_FLAGS BLIT_VK_CULL_DRAW_DEFAULT = 1;
	constexpr BLIT_VK_CULLING_FLAGS BLIT_VK_CULL_CLUSTER_DEFAULT = 10;
	constexpr BLIT_VK_CULLING_FLAGS BLIT_VK_CULL_DRAW_TEMPORAL_OCCLUSION = 5;

	using BLIT_VK_CULLED_OBJECT_TYPE = int8_t;
	constexpr BLIT_VK_CULLED_OBJECT_TYPE BLIT_VK_CULL_OBJECT_OPAQUE = 0;
	constexpr BLIT_VK_CULLED_OBJECT_TYPE BLIT_VK_CULL_OBJECT_TRANSPARENT = 1;
	constexpr BLIT_VK_CULLED_OBJECT_TYPE BLIT_VK_CULL_OBJECT_OPAQUE_DYNAMIC = 2;

	void DispatchCullingShaders(VulkanRenderer* pContext, uint32_t workCount, uint32_t workOffset, BLIT_VK_CULLING_FLAGS cullingFlags, BLIT_VK_CULLED_OBJECT_TYPE objectType);
}