#pragma once

#ifdef __cplusplus
	using uint = uint32_t;
#endif

static const uint BLIT_MAX_WORLD_RENDERS = 5000000;
static const uint BLIT_MAX_WORLD_OPAQUE_STATIC_RENDERS = 4500000;
static const uint BLIT_MAX_WORLD_TRANSPARENT_RENDERS = 10000;
static const uint BLIT_MAX_WORLD_OPAQUE_DYNAMIC_RENDERS = 5000;
static const uint BLIT_TRANSPARENT_RENDER_OFFSET = 0;
static const uint BLIT_OPAQUE_DYNAMIC_RENDER_OFFSET = BLIT_MAX_WORLD_TRANSPARENT_RENDERS;
static const uint BLIT_OPAQUE_STATIC_RENDER_OFFSET = BLIT_MAX_WORLD_TRANSPARENT_RENDERS + BLIT_MAX_WORLD_OPAQUE_DYNAMIC_RENDERS;
static const uint BLIT_MAX_WORLD_TRANSFORM_COUNT = BLIT_MAX_WORLD_RENDERS;