#include "blitzenWorldPrivate.h"

namespace BlitzenWorld
{
	inline static BlitzenPrivateContext* S_P_CONTEXT = nullptr;

	static void DispatchUpdate(BlitzenWorldUpdate& update, BlitzenPrivateContext& context)
	{
		for (uint32_t work = 0; work < update.m_worldUpdateWorkCount; ++work)
		{
			switch (update.m_worldUpdateFlags[work])
			{
			case WorldUpdateType::ADD_DYNAMIC_TRANSFORM:
			{
				BlitzenEngine::AddMovingEntitiesToManager(context.pEntityMangager, update.m_updateIDX[work]);
				break;
			}
			case WorldUpdateType::REMOVE_DYNAMIC_TRANSFORM:
			{
				BlitzenEngine::RemoveMovingEntitiesFromManager(context.pEntityMangager, update.m_updateIDX[work]);
				break;
			}
			case WorldUpdateType::NO_UPDATE:
			{
				break;
			}
			}
		}

		// reset
		update.m_worldUpdateWorkCount = 0;
		// next
		update.m_state = WorldUpdateState::DISPATCHED;
	}

	static void UpdateMovingEntities(BlitzenEngine::DynamicTransform** pMovingEntities, uint32_t count, BlitzenEngine::MeshTransform* pTransforms, BlitzenEngine::RendererPtrType pRenderer)
	{
		pRenderer->UpdateTransforms(pMovingEntities, count, pTransforms);
	}

	void UpdateLoop(BlitzenPrivateContext& context)
	{
		S_P_CONTEXT = &context;

		while (*context.pEngineState != BlitzenCore::EngineState::SHUTDOWN)
		{
			for (uint32_t work = 0; work < context.pBlitzenContext->worldUpdateCount; ++work)
			{
				while (context.pBlitzenContext->worldUpdates[work].m_state != WorldUpdateState::READY);// Wait
				DispatchUpdate(context.pBlitzenContext->worldUpdates[work], context);
			}

			UpdateMovingEntities(context.pEntityMangager->m_movingEntities.Get(), context.pEntityMangager->m_movingCount, context.pEntityMangager->m_renderContainer.m_transforms,
				context.pWORLD->P_RENDERER.Data());
		}
	}

	void S_WORLD_UPDATE_RECEIVER_SEND_TRANSFORM(BlitzenEngine::DynamicTransform* pTransform, uint32_t wvID)
	{
		BLIT_ASSERT_MESSAGE(S_P_CONTEXT->pBlitzenContext->worldUpdateCount < CE_WORLD_UPDATE_RECEIVER_MAX_WORK_COUNT, "Too much work generated by a single world variable");

		auto& update{ S_P_CONTEXT->pBlitzenContext->worldUpdates[wvID] };

		update.m_worldUpdateFlags[S_P_CONTEXT->pBlitzenContext->worldUpdateCount] = WorldUpdateType::ADD_DYNAMIC_TRANSFORM;
		update.m_updateIDX[S_P_CONTEXT->pBlitzenContext->worldUpdateCount] = pTransform->m_thisID;

		S_P_CONTEXT->pBlitzenContext->worldUpdateCount++;
	}
}