#pragma once

#ifdef __cplusplus
	using uint = uint32_t;
#endif

/****************************************************************************************************************************************************************************************
* THE MACROS IN THIS FILE ARE NOT TO BE CONVERTED TO CONSTEXPR AS THE FILE NEEDS TO BE INCLUDED IN SHADERS AS WELL																	    *
*****************************************************************************************************************************************************************************************/

#define BLIT_MAX_WORLD_VARIABLE_COUNT														5000u
#define BLIT_MAX_WORLD_RESIDENTS															5000000u
#define BLIT_MAX_WORLD_STATIC_RESIDENTS														4500000u
#ifdef __cplusplus
	static_assert(BLIT_MAX_WORLD_STATIC_RESIDENTS + BLIT_MAX_WORLD_VARIABLE_COUNT < BLIT_MAX_WORLD_RESIDENTS);
#endif
#define BLIT_MAX_WORLD_RENDERS																BLIT_MAX_WORLD_RESIDENTS
#define BLIT_MAX_WORLD_OPAQUE_STATIC_RENDERS												BLIT_MAX_WORLD_STATIC_RESIDENTS
#define BLIT_MAX_WORLD_OPAQUE_DYNAMIC_RENDERS												5000u
#define BLIT_OPAQUE_DYNAMIC_RENDER_OFFSET													0u
#ifdef __cplusplus
	static_assert(BLIT_OPAQUE_DYNAMIC_RENDER_OFFSET == 0);
#endif
#define BLIT_OPAQUE_STATIC_RENDER_OFFSET													BLIT_MAX_WORLD_OPAQUE_DYNAMIC_RENDERS
#define BLIT_MAX_WORLD_TRANSPARENTS															10000u
#define BLIT_TRANSPARENT_RENDER_OFFSET														4750000u
#ifdef __cplusplus
	static_assert(BLIT_TRANSPARENT_RENDER_OFFSET > BLIT_MAX_WORLD_STATIC_RESIDENTS + BLIT_OPAQUE_STATIC_RENDER_OFFSET);
#endif
#define BLIT_MAX_WORLD_TRANSFORM_COUNT														BLIT_MAX_WORLD_RENDERS

#define BLIT_MAX_STATIC_DRAW_COMMANDS														500000u
#ifdef __cplusplus
	static_assert(BLIT_MAX_STATIC_DRAW_COMMANDS <= BLIT_MAX_WORLD_OPAQUE_STATIC_RENDERS);
#endif

#define BLIT_MAX_DYNAMIC_DRAW_COMMANDS														5000u
#ifdef __cplusplus
	static_assert(BLIT_MAX_DYNAMIC_DRAW_COMMANDS <= BLIT_MAX_WORLD_OPAQUE_DYNAMIC_RENDERS);
#endif

#define BLIT_MAX_INSTANCED_RENDERS															1000000u
#define BLIT_MINIMUM_INSTANCE_COUNT_THRESHOLD												10000u

#define BLIT_MAX_CLUSTER_GROUPS																1000000u
#define BLIT_MAX_CLUSTERS_PER_GROUP															64u
#define BLIT_MAX_CLUSTER_DRAW_COMMANDS														500000u
#ifdef __cplusplus
	static_assert(BLIT_MAX_CLUSTER_DRAW_COMMANDS <= BLIT_MAX_CLUSTER_GROUPS);
#endif

#define BLIT_MAX_WORLD_TEXTURE_RESOURCES													5000u

#define BLIT_COLLISION_GRID_EXTENT															3200u
#define BLIT_COLLISION_GRID_CELL_EXTENT														64u
#define BLIT_COLLISION_GRID_CELL_FLAT_COUNT													(BLIT_COLLISION_GRID_EXTENT / BLIT_COLLISION_GRID_CELL_EXTENT)
#ifdef __cplusplus
	static_assert(BLIT_COLLISION_GRID_CELL_FLAT_COUNT == BLIT_COLLISION_GRID_EXTENT / BLIT_COLLISION_GRID_CELL_EXTENT);
#endif
#define BLIT_COLLISION_GRID_CELL_COUNT														(BLIT_COLLISION_GRID_CELL_FLAT_COUNT * BLIT_COLLISION_GRID_CELL_FLAT_COUNT)
#ifdef __cplusplus
	static_assert(BLIT_COLLISION_GRID_CELL_COUNT == BLIT_COLLISION_GRID_CELL_FLAT_COUNT * BLIT_COLLISION_GRID_CELL_FLAT_COUNT);
#endif

#define BLIT_COLLIDER_SCALE_MULTIPLIER														1.f
#define BLIT_COLLIDER_COUNT_PER_GRID_CELL													(BLIT_COLLISION_GRID_CELL_EXTENT / BLIT_COLLIDER_SCALE_MULTIPLIER)
#define BLIT_AVAILABLE_COLLIDER_SPACES														(BLIT_COLLIDER_COUNT_PER_GRID_CELL * BLIT_COLLISION_GRID_CELL_COUNT)
#ifdef __cplusplus
	static_assert(BLIT_COLLIDER_COUNT_PER_GRID_CELL == BLIT_COLLISION_GRID_CELL_EXTENT / BLIT_COLLIDER_SCALE_MULTIPLIER);
	static_assert(BLIT_AVAILABLE_COLLIDER_SPACES == (BLIT_COLLIDER_COUNT_PER_GRID_CELL * BLIT_COLLISION_GRID_CELL_COUNT));
#endif

#define BLIT_DYNAMIC_COLLIDER_COUNT_PER_GRID_CELL											(BLIT_COLLISION_GRID_CELL_EXTENT / BLIT_COLLIDER_SCALE_MULTIPLIER)
#define BLIT_AVAILABLE_DYNAMIC_COLLIDER_SPACES												(BLIT_DYNAMIC_COLLIDER_COUNT_PER_GRID_CELL * BLIT_COLLISION_GRID_CELL_COUNT)
#ifdef __cplusplus
		static_assert(BLIT_DYNAMIC_COLLIDER_COUNT_PER_GRID_CELL == BLIT_COLLISION_GRID_CELL_EXTENT / BLIT_COLLIDER_SCALE_MULTIPLIER);
		static_assert(BLIT_AVAILABLE_DYNAMIC_COLLIDER_SPACES == (BLIT_DYNAMIC_COLLIDER_COUNT_PER_GRID_CELL * BLIT_COLLISION_GRID_CELL_COUNT));
#endif

#define BLIT_TERRAIN_GRID_SIZE_TEMP															64
#define BLIT_MAX_HEIGHT_MAP_DATA_COUNT														(BLIT_TERRAIN_GRID_SIZE_TEMP * BLIT_TERRAIN_GRID_SIZE_TEMP)
#ifdef __cplusplus
		static_assert(BLIT_MAX_HEIGHT_MAP_DATA_COUNT == BLIT_TERRAIN_GRID_SIZE_TEMP * BLIT_TERRAIN_GRID_SIZE_TEMP);
#endif

#define BLIT_GRAVITATIONAL_ACCELERATION														0.1f
#define BLIT_TERRAIN_HEIGHT_TEST_VALUE														0.f

/************************************************************************************************************************************************
* DX12 REGISTERS																																*
*************************************************************************************************************************************************/
#ifdef __cplusplus
	constexpr uint BLIT_HLSL_OPAQUE_STATIC_CMD_BUFFER_REGISTER = 0;
	constexpr uint BLIT_HLSL_OPAQUE_STATIC_CMD_COUNTER_REGISTER = 1;
	constexpr uint BLIT_HLSL_OPAQUE_DYNAMIC_CMD_BUFFER_REGISTER = 2;
	constexpr uint BLIT_HLSL_OPAQUE_DYNAMIC_CMD_COUNTER_REGISTER = 3;
	constexpr uint BLIT_HLSL_SHADER_TRANSFORM_BUFFER_REGISTER = 4;
	constexpr uint BLIT_HLSL_CLUSTER_GROUP_BUFFER_REGISTER = 5;
	constexpr uint BLIT_HLSL_CLUSTER_COUNTER_BUFFER_REGISTER = 6;
	constexpr uint BLIT_HLSL_CLUSTER_VISIBILITY_BUFFER_REGISTER = 7;
	constexpr uint BLIT_HLSL_CLUSTER_CMD_BUFFER_REGISTER = 8;
	constexpr uint BLIT_HLSL_CLUSTER_CMD_COUNTER_REGISTER = 9;
	constexpr uint BLIT_HLSL_OCCDP_VISIBILITY_REGISTER = 10;
	constexpr uint BLIT_HLSL_INSTANCED_CMD_BUFFER_REGISTER = 11;
	constexpr uint BLIT_HLSL_INSTANCED_CMD_COUNTER_REGISTER = 12;
	constexpr uint BLIT_HLSL_HI_Z_OUTPUT_REGISTER = 13;
	constexpr uint BLIT_HLSL_WVTRANSFORM_BUFFER_REGISTER = 14;
	constexpr uint BLIT_HLSL_GRID_CELLS_REGISTER = 15;
	constexpr uint BLIT_HLSL_COLLIDER_IDXs_REGISTER = 16;
	constexpr uint BLIT_HLSL_COLLIDER_FLOAT3_AMAXRAD_REGISTER = 17;
	constexpr uint BLIT_HLSL_COLLIDER_FLOAT3_BMINTYPE_REGISTER = 18;
	constexpr uint BLIT_HLSL_GLOBAL_COLLIDER_IDXs_OFFSET_REGISTER = 19;

	constexpr uint BLIT_HLSL_RENDER_BUFFER_REGISTER = 0;
	constexpr uint BLIT_HLSL_BOUNDING_SPHERE_REGISTER = 1;
	constexpr uint BLIT_HLSL_SURFACE_BUFFER_REGISTER = 2;
	constexpr uint BLIT_HLSL_TERRAIN_HEIGHT_BUFFER_REGISTER = 3;
	constexpr uint BLIT_HLSL_LOD_BUFFER_REGISTER = 4;
	constexpr uint BLIT_HLSL_HI_Z_MAP_REGISTER = 5;
	constexpr uint BLIT_HLSL_CLUSTER_VTXS_REGISTER = 6;
	constexpr uint BLIT_HLSL_CLUSTER_SPHERES_REGISTER = 7;
	constexpr uint BLIT_HLSL_CLUSTER_CONES_REGISTER = 8;
	constexpr uint BLIT_HLSL_VTX_POSITIONS_REGISTER = 9;
	constexpr uint BLIT_HLSL_VTX_NORMALS_REGISTER = 10;
	constexpr uint BLIT_HLSL_VTX_TANGENTS_REGISTER = 11;
	constexpr uint BLIT_HLSL_VTX_TEXCOORDS_REGISTER = 12;
	constexpr uint BLIT_HLSL_MATERIAL_BUFFER_REGISTER = 13;
	constexpr uint BLIT_HLSL_HI_Z_INPUT_REGISTER = 14;
	constexpr uint BLIT_HLSL_INSTANCED_RENDERS_REGISTER = 15;
	constexpr uint BLIT_HLSL_TERRAIN_VERTEX_POSITIONS_REGISTER = 16;
	constexpr uint BLIT_HLSL_TEXTURE_DESCRIPTORS_REGISTER = 17;

	constexpr uint BLIT_HLSL_VIEW_DATA_REGISTER = 0;
	constexpr uint BLIT_HLSL_OPAQUE_STATIC_COUNT_CONSTANT_REGISTER = 1;
	constexpr uint BLIT_HLSL_OPAQUE_DYNAMIC_COUNT_CONSTANT_REGISTER = 2;
	constexpr uint BLIT_HLSL_OPAQUE_STATIC_OBJID_REGISTER = 3;
	constexpr uint BLIT_HLSL_OPAQUE_DYNAMIC_OBJID_REGISTER = 4;
	constexpr uint BLIT_HLSL_OPAQUE_INSTANCED_OBJID_REGISTER = 5;
	constexpr uint BLIT_HLSL_HI_Z_CONTANT_REGISTER = 6;
	constexpr uint BLIT_HLSL_CLUSTER_OBJID_REGISTER = 7;
	constexpr uint BLIT_HLSL_CLUSTER_WORK_COUNT_CONSTANT_REGISTER = 8;
	constexpr uint BLIT_HLSL_INSTANCE_WORK_COUNT_REGISTER = 9;

	constexpr uint BLIT_HLSL_TEX_SAMPLER_REGISTER = 0;

	constexpr uint BLIT_HLSL_BLITZEN_LOGO_TEX_REGISTER = 0;
#endif

enum BLIT_RESIDENT_MOVEMENT_FLAG_BITS
{
	BLIT_RESIDENT_MOVEMENT_NONE = 0,
	BLIT_RESIDENT_MOVEMENT_ROTATING_YAW_BIT = 1 << 0,
	BLIT_RESIDENT_MOVEMENT_ROTATING_PITCH_BIT = 1 << 1,
	BLIT_RESIDENT_MOVEMENT_ROTATING_ROLL_BIT = 1 << 2, 
	BLIT_RESIDENT_MOVEMENT_GRAVITY_BIT = 1 << 3,
	BLIT_RESIDENT_MOVEMENT_FALLING_BIT = 1 << 4,
	BLIT_RESIDENT_MOVEMENT_VELOCITY_ZAXIS_BIT = 1 << 5,
	BLIT_RESIDENT_MOVEMENT_VELOCITY_XAXIS_BIT = 1 << 6,
	BLIT_RESIDENT_MOVEMENT_VELOCITY_YAXIS_BIT = 1 << 7,
};

enum BlitColliderType
{
	AABB,
	Capsule,
	Sphere
};
#ifdef __cplusplus
	static_assert(sizeof(BlitColliderType) == 4);
#endif

#ifdef __cplusplus
	enum BLITZEN_COLLISION_IDENTIFIER : uint64_t
	{
		BLITZEN_COLLISION_FLAGS_IGNORE = 0x0,
		BLITZEN_COLLISION_FLAGS_BLOCK = 0x1
	};

	enum WORLD_VARIABLE_CATEGORY : uint64_t
	{
		BLITZEN_WORLD_VARIABLE_UNSPECIFIED = 0x0,
	};

	using WORLD_VARIABLE_IDENTIFIER = uint32_t;
#endif

#define BMPR_DRIVE_BROAD_PHASE_COLLISION				1
#define BMPR_DRIVE_NARROW_PHASE_COLLISION				0
#ifdef __cplusplus
	#if BMPR_DRIVE_BROAD_PHASE_COLLISION == 0
		constexpr uint8_t BLITGCBroadPhaseCollisionBumper = 0;
	#else
		constexpr uint8_t BLITGCBroadPhaseCollisionBumper = 1;
	#endif
	#if BMPR_DRIVE_NARROW_PHASE_COLLISION == 0
		constexpr uint8_t BLITGCNarrowPhaseCollisionBumper = 0;
	#else 
			constexpr uint8_t BLITGCNarrowPhaseCollisionBumper = 1;
	#endif
#endif